In [4]:
import import_ipynb
import Location
from Location import *
from Enum_profile import *
from Profile import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Read Data

In [5]:
data = pd.read_csv('C:/Users/EL FASHKA/Desktop/FABB/Recherches/Projet Simulation/Exple.csv', sep = ";")
index = pd.date_range(start='1/1/2020', periods=8784, freq = '1h00t')
data['time'] = index
data.set_index('time', inplace = True)
data.drop(['Date','Heures'], axis = 1,inplace = True)

In [6]:
# Solar park installed in 2020 = 10020
data['Solaire_kwh']= data['Solaire']/10020
data

,Conso_stade,Conso_scolaire,Conso_inactif,Conso_Actif,Solaire,Solaire_kwh
time,,,,,,
2020-01-01 00:00:00,0.561,2.64,0.86,0.86,0.0,0.0
2020-01-01 01:00:00,0.495,2.25,0.73,0.73,0.0,0.0
2020-01-01 02:00:00,0.297,1.95,0.60,0.90,0.0,0.0
2020-01-01 03:00:00,0.297,1.98,0.60,0.90,0.0,0.0
2020-01-01 04:00:00,0.297,1.80,0.60,0.90,0.0,0.0
...,...,...,...,...,...,...
2020-12-31 19:00:00,0.660,1.15,2.26,2.26,0.0,0.0
2020-12-31 20:00:00,0.627,1.95,1.40,1.40,0.0,0.0
2020-12-31 21:00:00,0.597,0.49,1.86,1.86,0.0,0.0
2020-12-31 22:00:00,0.561,1.80,1.27,1.26,0.0,0.0
2020-12-31 23:00:00,0.528,1.60,1.20,1.20,0.0,0.0